--- #YAML:1.0
name:               Email-Send-Gandi
version:            0.34
abstract:           Send Messages using Gandi
author:
    - Leon Brocard <acme@astray.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Authen::SASL:    0
    Email::Address:  0
    Email::Send:     0
    Net::SMTP::SSL:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
